export const ROUTES = {
  HOME: "/",
  PRODUCTS: "/products",
  PRODUCT_DETAILS: (slug: string) => `/products/${slug}`,
  COLLECTIONS: "/collections",
  COLLECTION_DETAILS: (slug: string) => `/collections/${slug}`,
  SEARCH: "/search",
  STORY: "/story",
  CONTACT: "/contact",
  CHECKOUT: "/checkout",
  CHECKOUT_SUCCESS: "/checkout/success",
  CHECKOUT_FAILED: "/checkout/failed",
  CHECKOUT_TRACK: "/checkout/track",
  ORDER_TRACK: (orderId: string) => `/order/${orderId}`,
  REVIEW: (token: string) => `/review/${token}`,
  RETURN: (token: string) => `/return/${token}`,
  INVOICE: (token: string) => `/invoice/${token}`,
  RETURN_POLICY: "/return-policy",
  PRIVACY: "/privacy",
  TERMS: "/terms",
} as const;
